# Configuraciones del servidor
server:
  port: 8090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8082/realms/avaliacao
        registration:
          keycloak-registration:
            provider: keycloak-provider
            client-id: gateway
            client-secret: xwoELABhK23aqdGVbZ4xVog02oKhx6se
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Portão de entrada de serviços e encaminhamento de token.
  author: Rener Almeida
  severity: Alto