spring:
  application:
    name: ms-users
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "http://localhost:8082/realms/avaliacao/protocol/openid-connect/certs"
server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Serviço de usuários.
  author: Rener Almeida
  severity: Alto
